### ISSUE TITLE
clarify mysql_root_pass attribute

### ISSUE THREAD

**Issue by dergachev** [evolvingweb/chef-drupal-solr#1]
No such attribute exists in https://github.com/amirkdv/chef-drupal-solr/blob/master/attributes/default.rb

Why is it referenced in README.md?

**Comment by amirkdv** [comment]
The entry in README.md was a memo, sorry. I should have left it out until the change was made in the code. The attribute is intended to replace reference to `node['mysql']['server_root_password']` [here](https://github.com/amirkdv/chef-drupal-solr/blob/master/recipes/default.rb#L13), so the cookbook does not _require_ that you use the mysql cookbook to get your mysql server.

**Comment by dergachev** [comment]
Cool. I'm kinda happy about not having to set an extra attribute though...

## 

Alex Dergachev
Evolving Web, co-founder and lead developer
http://evolvingweb.ca :: web design & development
phone 514.844.4930 :: fax 514.807.7499
114-300 rue du Saint-Sacrement, Montréal, QC
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)
